incomplete entries were causing issues
{u'complete': False, u'address': u'192.168.0.220', u'dynamic': True, u'invalid': False, u'disabled': False, u'.id': u'*13', u'published': False, u'interface': u'ether1', u'DHCP': False}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "napalm_ros/ros.py", line 48, in get_arp_table
    'mac': cast_mac(entry['mac-address']),
KeyError: u'mac-address'